### PR TITLE
Update hackney dependency to 1.6 or 1.7

### PR DESCRIPTION
**Pull request by lessless**
1.0 got a bit old and conflicts with other packages

### CODE REVIEW

**Comment by lau** [comment]
Hi. `~> 1.0` means anything starting with `1.` is allowed. What error message do you get when trying to use version `1.6` or `1.7` of hackney?

**Comment by lessless** [comment]
Hi @lau !

I didn't notice that version specification has only major and minor number, I hope Mix really works that way.

The error was:
```
Unchecked dependencies for environment dev:
* hackney (Hex package)
  the dependency hackney 1.8.0

  > In deps/tzdata/mix.exs:
    {:hackney, "~> 1.0", [env: :prod, hex: "hackney", repo: "hexpm", optional: false, manager: :rebar3]}

  does not match the requirement specified

  > In deps/ex_aws/mix.exs:
    {:hackney, "1.6.3 or 1.6.5 or 1.7.1", [env: :prod, repo: "hexpm", hex: "hackney", optional: true]}

```

**Comment by d-mart** [comment]
I'm having the same issue trying to upgrade hackney and landed here researching it.  Appreciate any conclusions you reach on the actual source of the hackney version bind, @lessless.

**Comment by lessless** [comment]
Hello @d-mart, 
I don't remember the exact way to fix it but, something as simple as relaxing dependency requirements may help.
Can you please post the exact error message? There should be a mention of the library that is on the other side of the conflict.

**Comment by d-mart** [comment]
@lessless Thanks for the follow-up.  It seems a dependency of a dependency had an old hackney version pinned.  I'm in the process of unraveling it.

**Pull request closed without merging**
