### PR TITLE
Make Public API smaller

### PR DESCRIPTION
**Pull request by wojtekmach**
I made parts private somewhat arbitrarily. I split this into multiple commits so feel free to take as much or as little as you want. Since master is `v1.0.0-dev` it's an important conversation to have, what's public and what's private.

Thanks for creating and maintaining this library over the years!

### CODE REVIEW

**Comment by lau** [comment]
Thank you.

**Comment by lau** [comment]
There are conflicts, but I did at `@moduledoc false` to a number of modules. I haven't gone over the specs changes, but I think they might have conflicted with another PR that was merged first. If there are spec changes you think should be merged, a new PR or rebasing this one to fix conflicts is welcomed.

**Comment by wojtekmach** [comment]
@lau what's on master looks good to me, closing this.

**Comment by wojtekmach** [comment]
The only minor change I'd consider is replacing a custom type:

[`Tzdata.time_zone_name()`](https://github.com/lau/tzdata/blob/95fe420a6018d9aa9a02f76ea87063a3c805b6e0/lib/tzdata.ex#L12)

with the one from stdlib:

[`Calendar.time_zone()`](https://hexdocs.pm/elixir/Calendar.html#t:time_zone/0) 

WDYT? Happy to send a PR.

**Comment by lau** [comment]
> with the one from stdlib:
>
> [`Calendar.time_zone()`](https://hexdocs.pm/elixir/Calendar.html#t:time_zone/0)
>
> WDYT? Happy to send a PR.

That sounds good

**Pull request closed without merging**
