### PR TITLE
new implementation of PeriodBuilder

### PR DESCRIPTION
**Pull request by paulswartz**
When looking into some issues with periods being generate which go into the past, I wasn't able to fix them without a lot of restructuring of the PeriodBuilder. This PR is the result of that restructuring.

The main change is how rules are calculated. Rather than finding all the transitions for a year, we only find the next transition. We then generate a period and update the current state to have the data from the rule transition. There are definitely some places (esp. around calculating the next rule transition) that could be more efficient, but I wanted to check in about the general approach before optimizing.

The new files (implementation and test) are formatted with the Elixir 1.6 formatter.

### CODE REVIEW

**Comment by lau** [comment]
Hi Paul,

Thank you. It is great to see contributions to these nitty-gritty parts of Tzdata.

Why not replace `Tzdata.PeriodBuilder` instead of adding a new module and aliasing it?

**Comment by paulswartz** [comment]
I definitely will before merging: I figured it would be easier to see/review the module as a new file instead of a diff with the existing module.

If you're okay with the general approach (and with replacing the existing PeriodBuilder) then I'll move forward along that path.

**Comment by paulswartz** [comment]
@lau this should be ready to review/merge. It replaces the old builder completely, and cleans up some of the inefficiencies I could easily see.

**Comment by lau** [comment]
Hi Paul. It looks good.

Would you mind taking out the `update tzdata database to 2018d (and fix test)` part so that can be separate from this PR?

**Comment by paulswartz** [comment]
That introduces a race condition with the tests. If you run them and the ETS table is updated, the next run will fail. I'll open a new PR with just that change.

**Pull request merged**
