### PR TITLE
Httpc

### PR DESCRIPTION
**Pull request by polymetis**
Hey Lau, 

I was just doing some basic work to get hackney et al. out of tzdata and got the ssl checks and downloads with httpc, the native ssl module,  and the mozilla cacert.pem (as it is ubiquitous at this juncture) 

@dch and I have tested this a bit (Man in the middle attacks and cross platform) so we know it works to a degree.  

There are still a couple of todos that I have to do (Make the cacert file location configurable, documentation, and make the specs better)   but I thought I would get some of your thoughts on it as I am working.

### CODE REVIEW

**Comment by lau** [comment]
Hey. I think it would be really nice to have less dependencies. The main reason for using hackney is security. That https and certificate checking works and making sure that the data is actually from iana.org.

@ericmj what do you think? Is it possible to download a file securely with httpc? I remember a long time ago you saying something about certificate checking not being the only issue.

**Comment by polymetis** [comment]
Yep I saw the readme. :) 

Basically I did this. 

https://github.com/lau/tzdata/blob/e3d404c3a1add42744e0568064cde0f1f18e960b/lib/tzdata/http_client.ex#L55-L84

And included the mozilla cacert file (it weighs a bit less than all the dependencies). I can't remember when this feature hit erlang (I think 18 maybe) but it does check iana certs before allowing it to go through. 

I did a man in the middle attach (pointed iana at my own server) which stopped failed the tls and tested it more generically on https://badssl.com/

So theoretically it works. Also had @dch bang on it and it passed his muster.

**Comment by wojtekmach** [comment]
If for any reason hackney should stay as the default http client,  it'd be great to make it swappable.

This could be achieved by adding `optional: true` to hackney dependency and adding a http client behaviour and an hackney-based default implementation, similarly to how ex_aws does it [1] [2]

I'd be happy to help with adding this configurability and I think it'd be good to have it before v1.0.

[1] https://github.com/ex-aws/ex_aws/blob/v2.1.0/lib/ex_aws/request/http_client.ex
[2] https://github.com/ex-aws/ex_aws/blob/v2.1.0/lib/ex_aws/request/hackney.ex

**Comment by ericmj** [comment]
I would recommend not fetching the database at all. The database is fetched to priv/ which means it will get overwritten when a new release is made. It's common to deploy using containers or at least use some transient storage which means the database will also be overwritten on every restart. This can lead to scenario where your application is switching between the old and new database or even that some nodes of your application is using the new one while others are using the old one. I have not run into this scenario but I believe it can lead to some hard to diagnose bugs.

This also means we can remove hackney and it's 7 dependencies, which I think is an unfortunately heavy dependency on a light weight library such as tzdata.

What I instead recommend is to move out the database to a separate dependency that only holds the database file. This database should only hold the database file and can be updated independently from  tzdata.  We do this in mint [1] for the certificate store [2].

[1] https://github.com/ericmj/mint
[2] https://github.com/ericmj/castore

**Comment by lau** [comment]
@polymetis, @wojtekmach, @ericmj  thank you for the input.

> The database is fetched to priv/ which means it will get overwritten when a new release is made.

For releases it is recommended to configure Tzdata to use a directory other than priv. That way it will not be overwritten on new deploys.

The problems of not having automatic updates is that developers do not read the readme and do not realize how often time zone information change. Between Christmas and new years 2018 there were two updates. Most people don't have a process in place to do that manually. And why should they when there is software that can do it?

The purpose of this library is not to just have some outdated information about time zones, but rather to have the newest information available. Less dependencies are great. But libraries usually have dependencies because they bring some functionality. Having time zone data be out of date can cause serious issues.

An idea for a future version (after 1.0) is to have optional dependencies that provide secure HTTPS, but by default at least check for new updates using `httpc`. This check could issue an alert if a new version was found, but not actually update the data. If hackney or mint is present (optional dependencies), they could be used to fetch data securely and do the update. And as always people can easily change the default configuration.

Besides warnings and automatic updates, there could also be different strategies for updates. For instance with delayed updates where alerts are issued on new databases and then an update happens automatically within for instance 48 hours. Maybe a way to tell all nodes to update at a certain time of day (UTC).

**Comment by ericmj** [comment]
> For releases it is recommended to configure Tzdata to use a directory other than priv. That way it will not be overwritten on new deploys.

It's great that this is in the documentation 👍 but I think for most deploys using containers they don't have persistent storage and adding that creates additional operation complexity. In my experience with hex and where I have worked I have never deployed Elixir services with persistent instance storage. This is my experience though and may not be representative.

> The problems of not having automatic updates is that developers do not read the readme and do not realize how often time zone information change. Between Christmas and new years 2018 there were two updates. Most people don't have a process in place to do that manually. And why should they when there is software that can do it?

This is more often I thought and I have close to zero experience in this area so definitely take my thoughts with a grain of salt. One interesting thing to look at would be how long in advance an update is my made. I would think that a change to the database is done in long advance until it is in effect. So the actual number of updates may be less interesting compared to how long advance an update is made.

**Comment by wojtekmach** [comment]
> Less dependencies are great. But libraries usually have dependencies because they bring some functionality. 

For things like HTTP clients (and JSON parsers etc - basically whenever there are multiple packages solving common problem) it's very easy to run into a situation that your particular project, by way of transitive dependencies, ends up depending on multiple http clients (and multiple CA stores etc).

Since virtually everyone dealing with time zones in Elixir will (one way or another) depend on tzdata, I think it's crucial to keep it's dependencies as small as possible, especially as it reaches 1.0. However, it's also important to have good defaults and good out of the box experience, and I think we can achieve that while also making hackney optional.

**Comment by lau** [comment]
@ericmj The time from a change is announce until it takes effect varies. Sometimes months, sometimes weeks, sometimes days. It has happened that a country has issued a change with 1 day of notice before a time zone change was to take effect.

@wojtekmach Tzdata has been depending on hackney for years. And I have been thinking about ways to get rid of it while keeping the same functionality. Years ago httpoison was a dependency but that was removed in favor of just hackney. I think it was around the same time I talked to @ericmj on IRC about the possibility of using just `httpc` securely for HTTPS. Of course I don't want excessive dependencies. I don't like that either. But you can go to any project and argue that it should get rid of all of its dependencies even if it means less functionality. Does postgrex need to have dependencies to help connect to a database if you can just put all of your data statically in a private hex package instead? ;)

I do want to change the dependency, but I would prefer to not do it for 1.0.0 because it will just delay the release. The release candidate is already out. Elixir 1.8 has been out for little a while and there is no Tzdata release to enable the TimeZoneDatabase functionality. I think having a release soon is better than no release. And the current release candidate is code that has not changed that much in recent years. The good thing is that there are more numbers to chose from. I don't mind releasing a version 1.1 or 2.0 or 3.0.

As described earlier I think only having optional dependencies can be combined with using `httpc` to do insecure polling for the purpose of just alerting about new tzdata in case none of those dependencies are present. So that there is no hard dependencies on hackney, yet the default will at least help alert about problems with out of date data.

It would be easier to just not have this and just let most people think that the updates are infrequent and don't matter, but I have been in countries where a lot of problems were caused by the combination of time zone changes and systems that treated time zone data updates as code updates. And then did not update that data.

Hopefully now that people to a larger extent will add tzdata directly as a dependency (because of the new TimeZoneDatabase behaviour), they will be more likely to be aware of Tzdata being a part of their releases. And maybe more likely to think about how updates of the time zone data will take place in their system.

Again thanks for the input.

**Comment by wojtekmach** [comment]
> Of course I don't want excessive dependencies. I don't like that either. But you can go to any project and argue that it should get rid of all of its dependencies even if it means less functionality. Does postgrex need to have dependencies to help connect to a database if you can just put all of your data statically in a private hex package instead? ;)

Let me re-iterate that I want tzdata to keep providing good defaults and good out of the box experience, and at not point I was suggesting otherwise!

I know it was a joke, but funny that you mentioned Postgrex :) It depends on `db_connection` (which in turn depends on just `connection`, nothing else) and `decimal` (0 deps) and has an **optional** dependency on Jason. So it's actually a great example, it provides a minimal set of transitive dependencies and for things where there might be competing packages, it uses an optional default.

> I do want to change the dependency, but I would prefer to not do it for 1.0.0 because it will just delay the release. (...) I think having a release soon is better than no release. And the current release candidate is code that has not changed that much in recent years. 

That's totally understandable :+1:

I went ahead and created a PR anyway :) See: https://github.com/lau/tzdata/pull/78

**Comment by polymetis** [comment]
Just trying to follow along. Been under a bit of a pile . 

So ... I have a couple of questions. Have we answered whether or not httpc is secure enough to make this one request when provided with a cacert file (one provided for the batteries in approach)?  I am genuinely curious about the weakness in this regard. 

Now for the rationale of why I wrote this pull-request because I noticed hackney and it's supporting libraries in my app despite the fact that we only use httpc for small things and gun for larger things. This may be unusual in in the elixir ecosystem at present but with http2 coming into swing etc I suspect more people may move away from hackney. 

Another scenario that I have dealt with is when using one of the various forks of couchbeam you have to make a call between which version and hackney you are going to use and then deal with a bunch of bugs because couchbeam is much more advanced use of hackney. (This is probably part of the reason there a bazillion forks of couchbeam [along with it be vaguely orphaned] and seems, at least to me, to be a bit of waste of community time.) 

As @wojtekmach pointed out in #78 it might be a good idea to support hackney if present and this is such a trivial use of hackney it's unlikely to have problems the way couchbeam has but then again that's because it it's a trivial use.

And again this is just to explain my logic not as any form of authority on the matter but my engineer brain kinda broke it down this way. 

hackney: ubiquitous (partially because of tzdata) but has a lot of code and it's ubiquity is a two edge sword. 
ibrowse: has a two byte char problem (I am actually unsure if this is still a problem but it has nothing to do with the problem at hand) but this is a lateral move for hackney
gun: To many conflicts in cowlib until the cowboy 2 migration finishes. 

Comedy option: drag in the ssl stuff from either hackney or ibrowse

httpc: if secure it's in the vm and to be honest it's api changes are glacial so it's set and forget (we could boil down the cacert to just the particular part we need but that seemed to be overkill at least from developer time standpoint and if they change provider there would need to be a zeroday fix) 

Future Elixir Http Client:  There was some talk a while back of a inbuilt elixir http client (or at least the parts to make a client) which may a materialize at some point and that would preferable. 

Again not sure exactly where to land on this on but generally speaking I like my libraries to have a little executable code as possible and stay out of the way and I agree with @lau that we should be polling for new data because not every shop has the staffing to deal with this particular problem. @dch knows a bit more about http clients so he may weigh in. 

But I do think that either way we should block out the http client to it's own module at the very least. :P

**Comment by ericmj** [comment]
> So ... I have a couple of questions. Have we answered whether or not httpc is secure enough to make this one request when provided with a cacert file (one provided for the batteries in approach)? I am genuinely curious about the weakness in this regard.

Yes, with the right settings it is enough. This is what Mint sets up to get a safe by default HTTP client https://github.com/ericmj/mint/blob/master/lib/mint/core/transport/ssl.ex.

> Future Elixir Http Client: There was some talk a while back of a inbuilt elixir http client (or at least the parts to make a client) which may a materialize at some point and that would preferable.

You may be referring to Mint https://github.com/ericmj/mint. There were talks about including it in Elixir but it was scrapped and is instead a separate library now.

**Comment by mindreframer** [comment]
Here is a concrete example of how to use HTTPC in a secure fashion: 
- https://github.com/danschultzer/pow_assent/blob/master/lib/pow_assent/http_adapter/httpc.ex

**Comment by josevalim** [comment]
Btw, another option to use instead of hackney is Mint: https://elixir-lang.org/blog/2019/02/25/mint-a-new-http-library-for-elixir/

It is just two deps, compared to 7 in hackney. And operationally speaking it should be lighter than httpc.

**Comment by crertel** [comment]
@lau This looks good to me. I like the idea that this uses no additional dependencies beyond what's already in OTP.

**Comment by lau** [comment]
@polymetis Thank you for this PR. It is not a bad idea. And there has been a lot of good discussion around it. However after considering it and different alternatives, I prefer to not have to maintain the code for handling the certificate and the different options for HTTPS with httpc.

Also again thank you for everyone else that has provided input.

@josevalim Just replacing Hackney with Mint (and CA store) is an interesting option. My concerns are: if Mint is stable at this point and if it is worth it to make a release with that if there will be a new release not so long after: One that instead uses the before mentioned combination of optional dependencies and fall backs on only warnings. Perhaps it is worth it.

> Congratulations on v1.0!

Thanks!

I'm closing this and will look into a combination of optional dependencies (e.g. Mint or Hackney or something else implementing a behaviour) and warnings without updates (httpc if Mint or Hackney is not available).

**Pull request closed without merging**
