### PR TITLE
Fix/period overlaps

### PR DESCRIPTION
**Pull request by jarrodmoldrich**
Limit applied rules to zone line boundary and fix a number of edge cases.

Previously, when generating periods, when each zone line was processed,
the corresponding rules would be used to generate time periods according
to the range of years they encompassed.  This meant that any two zone
lines that switched between, for instance, daylight savings rules, could
potentially have periods generated that overlap the time period of prior
and subsequent time zones.  This caused some anomalies, such as periods
that went back in time, and nil periods, which would be cleaned up in a
post-process.

The algorithm has been modified to generate saner output which requires
no post-process step. During the generation of periods for each zone
line, the lower-limit is inferred from the end of the prior zone line,
and the upper limit is calculated for each new time period inferred from
the associated rule set of the zone line.  The rule set is followed
until a time period exhausts the upper limit.  If a period intersects
with either the lower or upper limit, the period's own lower and upper
limit will be truncated to fit inside those limits.

This means that the output should now generate periods where the
following conditions are met:

- the 'from' of a period will equal the 'until' of the prior period
- the 'until' of a period will equal the 'from' of the next period
- the 'until' of a period will always be greater than the 'from'

Thus there will be no overlaps.  In the case that a period is generated
with a matching 'from' and 'until', perhaps due to truncation, that
period will not be added to the list.

A test has been made to ensure these invariants hold for a number of
special cases found through the tzdata from `2020a`.  One of which has
disappeared from later versions of the tzdata, and so it makes sense to
keep this data separate.  An extra test function has been added to
permit parsing a single file outside of the usual test fixture.

During testing of the new algorithm, a bug was also found with the
ordering of rules.  Rule changes were ordered at month granularity, but
this causes issues where rule changes happen several times in a month,
e.g., during religious festivals.  The code has been updated to
calculate the day onset for each rule (which may change according to the
year) before sorting.

This PR also fixes the issue I raised some months ago: https://github.com/lau/tzdata/issues/102

### CODE REVIEW

**Comment by jarrodmoldrich** [comment]
Hi @lau. I had some unexpected work crop up, and so it took some time for me to circle back to this.  All up I spent about 20 hours on this.  At first I tried extending the post-process of the period list to fix the overlaps I was seeing, but after a number of attempts, I got it 95% of the way there, and hit the limit of what was possible after the tzdata information has been lost.  It felt like a band-aid anyway, so I changed tack to get a proper understanding of how the periods were generated, and then ensuring the data output was sane - as described in the PR.  The former approach is available in the first commit, and I think, by comparison, prevention was the better option.

Please give this a look over when you have the time, and let me know if it needs more work.  I'll probably use this internally for my own project until it hits upstream.

**Comment by lau** [comment]
@jarrodmoldrich This looks like a nice improvement. I haven't really had time to look at it so far, but expect to do so soon.

**Comment by jarrodmoldrich** [comment]
@lau Let me know if there's some way I can help this along?  I can go through on GitHub and put comments against each change, or we can try screenshare while we talk through it?  My hours are pretty flexible

**Comment by jarrodmoldrich** [comment]
@lau As per out discussion I have conducted some experiments to find if the new implementation has divergent results for `Tzdata.periods_for_time`.  I collated and merged all the period boundaries for both implementations, and found the results for `:utc` times 1 second before and after each boundary.  All results were the same for both implementations.  If you'd like I could pick some of these at random as verification, but I'm thinking the test that ensures the invariants are maintained (e.g., that all periods are consecutive) is probably enough.  If you think it would make sense to test for discrepancies in ':wall' results, I can do that too.

However, there were a few queries that raised an a `RuntimeException` of `dynamic periods assume 2 rules per year`.  This happened for `Africa/Casablanca` and `Africa/El_Aaiun` in Morocco, for times within the year 2062.  It appears Morocco has precomputed years up until 2037, which seems an exception to most time zones, and perhaps that's confusing the 'far future' calculations.  I haven't looked deeply into this.

**Comment by tapickell** [comment]
Hey just found this PR and hopefully it may resolve a recent issue we uncovered during the switch to Daylight Savings Time
For exactly one hour we were getting errors returned when trying to use code that uses the `Tzdata.periods_for_time` function call
Here is n example I was able to reproduce in IEX
```
iex(25)> tzs
"America/Los_Angeles"
iex(26)> g_dt
~U[2021-03-14 01:45:00Z] #before 2am UTC when switch happens and things break
iex(27)> b_dt
~U[2021-03-14 02:15:00Z] #after 2am UTC when switch happens and things break
iex(28)> good_seconds = Timex.to_gregorian_seconds(g_dt)  
63782905500
iex(29)> bad_seconds = Timex.to_gregorian_seconds(b_dt)   
63782907300
iex(30)> Tzdata.periods_for_time(tzs, good_seconds, :wall)
[
  %{
    from: %{standard: 63771411600, utc: 63771440400, wall: 63771411600},
    std_off: 0,
    until: %{standard: 63782906400, utc: 63782935200, wall: 63782906400}, 
    utc_off: -28800,
    zone_abbr: "PST"
  }
]
iex(31)> Tzdata.periods_for_time(tzs, bad_seconds, :wall) 
[]

```
We are hoping this PR will resolve this issue as it had a big impact on our services.
If not please let me know and I would like to help come up with a resolution for the next change.

**Comment by jarrodmoldrich** [comment]
Hi @tapickell ,

I just tried this on my version, and this doesn't appear to be a bug.  You're using the `:wall` time with a UTC timestamp.  The wall clock represents the UTC time + the time zone's UTC offset (-28800 or -8 hours for Los Angeles) + the 'standard offset' (which is either 0 for Pacific Standard Time or 3600 for Pacific Daylight Time in LA).  The time boundary you have found is an hour forwards, which means there's an hour of 'wall time' that doesn't exist.  If you're using UTC inputs, you might be better off using `:utc` and doing your calculations in UTC.  Queries at all times in `:utc` should give an answer.

**Comment by tapickell** [comment]
@jarrodmoldrich 
Thank you, this is very helpful, I did not understand the `:wall` vs `:utc` part of the function call very well.
Our bug actually originates in the Timex library and it passes the `:wall` parameter in on our failing test case.
I will dig deeper into that library to figure out why that is.

**Comment by lau** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by jarrodmoldrich** [comment]
Thanks for that, @lau.  It was great working with you 🙂

**Pull request merged**
